spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_ID}
    password: ${MYSQL_PASS}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments : true
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

file:
  path: C:/images
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket : ${S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

#Spring doc
springdoc:
  packages-to-scan:
    - com.a307.ifIDieTomorrow
  paths-to-match:
    - /*/**
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    path: /swagger

#Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always

# MatterMost Notification
notification:
  mattermost:
    webhook-url: ${MATTERMOST_URL}
    pretext: Web-BackEnd
    enabled: 'true'

# JWT Secret 설정
jwt:
  secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'